Blog app - integration specs for views and fix n+1 problems
WilhelmK109/BlogApp pull request #8
Opened 2023-08-28 14:58 UTC by WilhelmK109

### I this milestone of the project, I did the following:
- Fixed the N+1 problem when fetching all posts and their comments for a user.
- Used Capybara to write integration tests for each view in the project.
- Included integration spec for user index page features.
- Included integration spec for user show page features.
- Included integration spec for user post index page features.
- Included integration spec for post show page features.

2023-08-28 15:02 UTC, WilhelmK109 commented
before
![before](https://github.com/WilhelmK109/BlogApp/assets/74548443/9d9aa570-42fb-4d20-815f-85139608c9f6)

after
![after](https://github.com/WilhelmK109/BlogApp/assets/74548443/59c45bf9-49c2-4841-8df5-dbc5812d295a)

2023-08-29 18:39 UTC, mckent05 requested changes
Hi @WilhelmK109, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍
- Good job adding integration tests to your application 😄  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Since this is a pair-programming activity I suggest that your partner should have contributions to the project 🙏  
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 18:39 UTC, mckent05 commented on spec/view_integration/user_spec.rb
> +    end
- You have done well, but according to the project requirements, you should test that the user information for all users is displayed. Since you have created 2 users for your test. Please ensure that the info for the second  user is displayed 🙏

2023-08-29 18:39 UTC, mckent05 commented on spec/view_integration/user_spec.rb
> +    end
- You did well so far, but since you have the `three_most_recent_posts` method that returns the 3 most recent posts, I suggest that you use this method to return the most recent posts for the selected user. Please fix this 🙏

2023-08-29 18:39 UTC, mckent05 commented on spec/view_integration/post_spec.rb
> +    end
- You have done well so far, but according to the project requirements, you should test for the number of posts a user has written. Please fix this 🙏

2023-08-29 18:39 UTC, mckent05 commented on spec/view_integration/post_spec.rb
> +      expect(page).to have_content(post.comments_counter)
- Good job done so far, but according to the project requirements, you should have a test that asserts that you can see the first comments on a post. I suggest you use the method that returns the 3 most recent comments to do this. Please fix this 🙏 
- According to the project requirements, you should have a test that asserts you can see the number of likes a post has. Please fix this 🙏

2023-08-29 18:39 UTC, mckent05 commented on spec/view_integration/post_spec.rb
> +    end
- According to the project requirements, you should have a test that asserts you can see the number of likes a post has. Please fix this 🙏 
- According to the project requirements, you should have a test that asserts you can see the username of each commenter. Please fix this 🙏 
- According to the project requirements, you should have a test that asserts you can see the comment each commentor lef. Please fix this 🙏

2023-08-29 19:07 UTC, WilhelmK109 commented
@mckent05, thank you for your comments and suggestions. I will make the necessary changes and re-submit for a review.

2023-08-30 09:58 UTC, jerryowusu requested changes
Hi @WilhelmK109 & @Enning94 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close](https://github.com/WilhelmK109/BlogApp/assets/65233860/81c432a1-d5d3-43c4-871c-21c9492e4f68)


 ## Highlights
Neat code :100: 
Tests Passing :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 09:58 UTC, jerryowusu commented on spec/view_integration/post_spec.rb
> +end
- [ ] Well done so far. However, as requested by the previous reviewer, kindly add test that asserts that you can see the username of each commenter. I can see you have test for the username on line 12 but that is for the post itself and not the comments. :+1: 
- [ ] Kindly also consider writing test to assert that you can see the comment each commentor left. You seem to have missed that. Remember it is also part of the project requirements. :pray:

2023-08-30 09:58 UTC, jerryowusu commented on spec/view_integration/user_spec.rb
> +end
- [ ] [OPTIONAL] According to the project requirements, each group of tests should have one test file and should not be mixed together. For instance, featured tests for the `user post show page` should be in a separate file from the tests for the `User post index pag`e. same applies to the User index and User show page. You seem to have combined them. Kindly update accordingly. :pray: 


![Screenshot from 2023-08-30 09-55-30](https://github.com/WilhelmK109/BlogApp/assets/65233860/de912845-2f53-4b8a-b7db-9a9e84d4eae6)

2023-08-30 09:58 UTC, jerryowusu commented on spec/view_integration/post_spec.rb
> +  end
- [ ] [OPTIONAL] According to the project requirements, each group of tests should have one test file and should not be mixed together. For instance, featured tests for the `user post show page` should be in a separate file from the tests for the `User post index pag`e. same applies to the User index and User show page. You seem to have combined them. Kindly update accordingly. :pray: 


![Screenshot from 2023-08-30 09-55-30](https://github.com/WilhelmK109/BlogApp/assets/65233860/de912845-2f53-4b8a-b7db-9a9e84d4eae6)

2023-08-30 11:07 UTC, joel-kalema approved these changes
Hi Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 13:18 UTC, merged